### ISSUE TITLE
Handlerbars clientlibrary directive ignore value of minify flag

### ISSUE THREAD

**Issue by josmora** [DantaFramework/AEM#21]
This directive:

`{% clientLibrary "mycompany" type="js" minify="false" %}`  

Is going to use the minified version of the client library regardless the value set to **false**.

**Comment by jbarrera-xumak** [comment]
Hi @josmora-xumak, rules will be changed to behave as follows:
- Do not minify when the parameter 'minify' of the ClientLib helper is set to false although HTML Library Manager Minify option is set to true. 
- Force minify when HTML Library Manager Minify option is set to true and the parameter of the ClientLib helper is not being added.
