### ISSUE TITLE
Using resource properties that contain with ":" within their name

### ISSUE THREAD

**Issue by lduarte-xk** [DantaFramework/AEM#23]
I am not able to perform things such as: 

`{%content.jcr:title%}`

Using ":" is a very typical practice in JCR based apps, such as AEM, as this is how you define namespaces for your properties. As a practical example, suppose that I need to have custom metadata properties for an AEM Asset and I want remove any possibility of a collision with metadata property names from others.

Also all of the AEM out of the box components that deal with titles for example, use jcr:title as the property name

This seems to work alright for properties with ":" that are part of a cq:Page's jcr:content node, but not for other resources

Please add support for this.

Thanks

**Comment by dpolanco-xumak** [comment]
After reviewing the ticket we've confirmed that this is working as expected, instead we are going to work on a fix for the page context. However, if a project needs to use  some specific properties from those namespaces CPs can be added in order to include them
