### ISSUE TITLE
SlingModels cannot be used outside AEM Bundle

### ISSUE THREAD

**Issue by neozilon** [DantaFramework/AEM#25]
### Current behavior
When I create a SlingModel Class and configure it to use AddSlingModelsPropertiesContextProcessor it complains that the SlingModel Class is not found because the AEM bundle is not importing the class in OSGi 

### Expected behavior
It should add the SlingModel Data into the ContentModel

### Possible solution
Add DynamicImport in the OSGi Manifest for AEM Bundle

### Steps to reproduce (for bugs)
1. Configure a SlingModel in any bundle outside the AEM Bundle it will not work and will throw error

### Environment (for bugs)
* Danta versions: 1.0.0
* AEM version: 6.3
* Java version: 1.8

**Comment by jbarrera-xumak** [comment]
Fixed.
