### ISSUE TITLE
Null Pointer exception when trying to read Design context.

### ISSUE THREAD

**Issue by ptoc-xumak** [DantaFramework/AEM#48]
### Current behavior
Currently a null pointer exception is thrown when "AddDesignPropertiesContextProcessor" tries to access the designer style.

### Expected behavior
There should not be any null pointer exception when trying to read from Design context.

### Possible solution
To add the null validation. This is the current validation (lines 80 to 84):
```
if (style.getPath() != null) {
                Resource designResource = resourceResolver.getResource(style.getPath());
                Map<String, Object> designMap = (designResource != null) ? PropertyUtils.propsToMap(designResource) : new HashMap<String, Object>();
                contentModel.set(DESIGN_PROPERTIES_KEY, designMap);
}
```
This is how it could validate the null for "style":
```
if (style != null && style.getPath() != null) {
                Resource designResource = resourceResolver.getResource(style.getPath());
                Map<String, Object> designMap = (designResource != null) ? PropertyUtils.propsToMap(designResource) : new HashMap<String, Object>();
                contentModel.set(DESIGN_PROPERTIES_KEY, designMap);
}
```
### Steps to reproduce (for bugs)
1. In a 6.4 AEM instance, create a new page that wouldn't have any styles saved in designs folder.
2. Create a context processor that runs when the page is loaded.
3. In the context processor, add the code to access the Design context from the content model.
4. Build changes and deploy them to a local AEM 6.4.
5. Go to the new page that was just created so that the context processor tries to access to Design context.

### Environment (for bugs)
* Danta versions: 1.0.6
* AEM version: 6.4
* Java version: 1.8.0_144

**Comment by ehernandez-xk** [comment]
PR that closes this: https://github.com/DantaFramework/AEM/pull/49
